### PR TITLE
hugo-bin update, added babel-core to deps

### PR DESCRIPTION
**Pull request by atomtigerzoo**
**- Summary**

Hugo has gotten to a new version number and to reflect this change I updated the hugo-bin package. After testing this and clearing my local cache, I saw that babel-core seems to be missing in the project dependencies so I added that too.

**- Test plan**

Installed new packages and ran `gulp server` to verify that the page loads.

**- Description for the changelog**

Updated hugo-bin, added babel-core to dependencies

**- A picture of a cute animal (not mandatory but encouraged)**

Duckcat

### CODE REVIEW

**Comment by jhabdas** [comment]
🌮

**Comment by bdougie** [comment]
Were you getting errors from not having babel-core. 

It is my understanding that [babel-loader](https://github.com/babel/babel-loader) is already loading babel and the ideal way for projects using webpack. 

Can you remove that @atomtigerzoo

**Comment by atomtigerzoo** [comment]
Yes, I got an error that babel-core was missing. And as far as I understand it right on the babel-loader page, babel-core seems to be a dependency on install:

    npm install --save-dev babel-loader babel-core babel-preset-env webpack

Maybe most/some have had babel-core installed globally or just saw the error message and installed it right away?

I can test it on a clean OS and see if it installs without if you like.

**Comment by calavera** [comment]
it looks like this needs a rebase 🙏

**Comment by erquhart** [comment]
Rebased. Both [babel-loader](https://github.com/babel/babel-loader#install) and [gulp-babel](https://github.com/babel/gulp-babel#install) require babel-core to be installed, although it seems to come in as a dependency anyhow. Installing it directly is still good for making the dependency explicit.

**Pull request merged**
