### PR TITLE
Some - hopefully - nicer defaults

### PR DESCRIPTION
**Pull request by atomtigerzoo**
**- Summary**

For beginners and hopefully others, these changes should bring better default settings to the generated output of the first build. I disabled the RSS feed and the taxonomies to clean up the dist folder. The `title` and `baseURL` are now pulled from config and are added to the page's head. I also added a language parameter to the configuration and for output inside the head. Also changed and added some placeholder code in CSS and JS.

**- Test plan**

I have run `gulp server` and `npm run build` to review the changes. If you have had build the site before, you must empty the build beforehand since hugo does not clean the dist folder.

**- Description for the changelog**

Nicer default values for config and theme

**- A picture of a cute animal (not mandatory but encouraged)**

Mr. Fox

### CODE REVIEW

**Comment by chrisgeary92** [comment]
`disableRSS = true` is deprecated. It should be replaced with `disableKinds = ["RSS"]` 👌

**Comment by atomtigerzoo** [comment]
True - did not know about that :) Updated the PR accordingly.

**Comment by chrisgeary92** [comment]
I literally just found this out myself on something I was building. And remembered seeing your PR ;) I would have updated it for you, but don't think I can 👍

**Comment by calavera** [comment]
LGTM

**Pull request merged**
