### PR TITLE
Replace gulp.watch() with the gulp-watch package

### LINKED ISSUE #46: Gulp watch does not detect new layouts
For some reason the `gulp watch` tasks do not execute recursively – adding a new layout does not trigger the hugo task as it should according to the glob pattern.

Removing the `./` in the path of the watch tasks resolves the issue e.g:

```
  gulp.watch("src/js/**/*.js", ["js"]);
  gulp.watch("src/css/**/*.css", ["css"]);
  gulp.watch("site/**/*", ["hugo"]);
```

Running latest gulp on macOS:
```
$ gulp -v
[16:19:41] Requiring external module babel-register
[16:19:41] CLI version 1.4.0
[16:19:41] Local version 3.9.1
```

### PR DESCRIPTION
**Pull request by chrisgeary92**
Fixes #46 

**- Summary**

Currently you must stop the server/watcher and re-run to detect newly created files. This is cumbersome, and can be easily fixed by replacing the default `gulp.watch()` with the `gulp-watch` package (NPM).

**- Test plan**

```
npm install
npm run start
```

Terminal output before change == Terminal output after change

**- Description for the changelog**

`gulp.watch()` replaced with `gulp-watch` to detect new files

### CODE REVIEW

**Comment by jhabdas** [comment]
LGTM 👍 if in the future gulp is pulled this may be swapped with [`fs.watch()`](http://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener) or its cousin `fs.watchFile()`.

**Comment by bdougie** [comment]
@chrisgeary92 trying to understand the scope of this to confirm this is needed. When you say,  "adding files", What type of files are you referring to?

**Comment by chrisgeary92** [comment]
Any new file, new template, partial etc.

If I were to run `npm run start` then create a new file at `site/layouts/partials/header.html` it's not recognised by gulp watch, so changes to this file do not trigger a rebuild.. You have to `CTRL+C` to quit watching, then run `npm run start` again so it can watch the new header file.

More information can be found here: https://stackoverflow.com/questions/22391527/gulps-gulp-watch-not-triggered-for-new-or-deleted-files

**Comment by bdougie** [comment]
Thanks for the clarification and for the code for this. Made a note about fs.watchFile as well @jhabdas

**Pull request merged**
