### PR TITLE
Remove use gulp.start()

### PR DESCRIPTION
**Pull request by burmecia**
**- Summary**

gulp.start() is never officially supported by gulp, it's better to use the functionality provided by gulp.watch(). See: https://github.com/gulpjs/gulp/issues/755

**- Test plan**

Run `gulp server` to test.

**- Description for the changelog**

Remove use gulp.start()

**- A picture of a cute animal (not mandatory but encouraged)**

N/A

### CODE REVIEW

**Comment by heypaulmcgrath** [comment]
Not sure if you noticed something similar, but I tested this locally and it seems to kill Browsersync's auto-reload.

**Comment by burmecia** [comment]
@heypaulmcgrath yes you're right, the auto-reload doesn't work properly. The fix is to use gulp build-in `watch` function. So, it should be like this:

```javascript
  gulp.watch("./src/js/**/*.js", ["js"]);
  gulp.watch("./src/css/**/*.css", ["css"]);
  gulp.watch("./src/fonts/**/*", ["fonts"]);
  gulp.watch("./site/**/*", ["hugo"]);
```

And we can remove package `gulp-watch` as well.

**Comment by heypaulmcgrath** [comment]
Yup, that did the trick for me 👍

**Comment by burmecia** [comment]
This is replace by PR #66

**Pull request closed without merging**
